apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1   # 1 replica en nodo agente
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: application
    spec:
      # Asegurar que corre en nodo de aplicacion
      nodeSelector:
        node-type: application
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis   # se resuelve por DNS dentro del cluster
            - name: REDIS_PORT
              value: "6379"
