apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  # Configuracion de Redis master
  master.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    maxmemory 256mb
    maxmemory-policy allkeys-lru

  # Configuracion de Redis replica
  replica.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    replicaof redis-0.redis 6379

  # Configuracion de Sentinel
  sentinel.conf: |
    bind 0.0.0.0
    port 26379
    protected-mode no
    sentinel monitor mymaster redis-0.redis 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000
