apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1   # 1 replica en nodo agente
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: application
    spec:
      # Asegurar que corre en nodo de aplicacion
      nodeSelector:
        node-type: application
      containers:
        - name: web
          image: web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
